Install library

In [36]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [37]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [38]:
from google_play_scraper import app
import pandas as pd
import numpy as np

#scrape all available reviews

In [39]:
from numpy._core.defchararray import count
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.ss.android.ugc.trill',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=10000,
    filter_score_with=None
)

#show  data yang sudah di crawling

In [40]:
df_busu = pd.DataFrame(np.array(result),columns=['review']) #nama file bebas
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,90a0b45a-e5ab-48df-be71-6382d6b2804e,dina olivia,https://play-lh.googleusercontent.com/a-/ALV-U...,abia di up bukannya tambah bagus malah tambah ...,2,0,45.2.3,2026-05-21 00:45:36,"Hai, maaf atas ketidaknyamanannya. Agar kami b...",2026-05-21 01:00:10,45.2.3
9996,29e84c6a-d098-4dd5-84b1-8a40503eb064,Andi Rohania Patiroy,https://play-lh.googleusercontent.com/a-/ALV-U...,bagus,5,0,44.6.4,2026-05-21 00:44:03,Hai! Terima kasih telah meluangkan waktu untuk...,2026-05-21 01:00:10,44.6.4
9997,3cffe14c-2d28-4143-914a-6e08e27b2f5d,Mula Aritonang,https://play-lh.googleusercontent.com/a/ACg8oc...,Tdk bisa di download,5,0,None,2026-05-21 00:42:27,Hai! Terima kasih telah meluangkan waktu untuk...,2026-05-21 01:00:11,None
9998,786ad1b0-6019-46af-bb94-97f28baf9f4c,Dapa Dapa,https://play-lh.googleusercontent.com/a/ACg8oc...,saya kasih bintang 2 karna konten saya tidak fyp,2,0,45.2.3,2026-05-21 00:39:38,None,NaT,45.2.3
9999,d1bd436e-2134-457b-a684-064543105530,Ali Imron,https://play-lh.googleusercontent.com/a-/ALV-U...,"apk gobl*k, saldo refund bisa ditarik harus mi...",1,0,45.2.3,2026-05-21 00:38:14,"Hai, terima kasih atas umpan balikmu!\nKami pa...",2026-05-21 01:00:10,45.2.3

In [41]:
len(df_busu.index)

10000

#ambil data yang dibutuhkan

In [42]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,dina olivia,2,2026-05-21 00:45:36,abia di up bukannya tambah bagus malah tambah ...
9996,Andi Rohania Patiroy,5,2026-05-21 00:44:03,bagus
9997,Mula Aritonang,5,2026-05-21 00:42:27,Tdk bisa di download
9998,Dapa Dapa,2,2026-05-21 00:39:38,saya kasih bintang 2 karna konten saya tidak fyp
9999,Ali Imron,1,2026-05-21 00:38:14,"apk gobl*k, saldo refund bisa ditarik harus mi..."

In [43]:
my_df =df_busu[['userName', 'score', 'at', 'content']]

In [44]:
#simpan dataset ke dalam file
my_df.to_csv("Datasettiktok", index = False)