#Instal library

In [12]:
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)

In [13]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [14]:
from google_play_scraper import app
import pandas as pd
import numpy as np

#scrape all available reviews

In [15]:
from numpy._core.defchararray import count
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.netflix.mediaclient',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=10000,
    filter_score_with=None
)

#show dta yang sudah di crawling

In [16]:
df_busu = pd.DataFrame(np.array(result),columns=['review']) #nama file bebas
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
9995,c1fab9bf-0b5d-4038-8164-7cbd77a7d637,Agus Helmi MK,https://play-lh.googleusercontent.com/a-/ALV-U...,Mantap,5,0,8.140.1 build 14 51170,2024-12-04 13:50:01,None,None,8.140.1 build 14 51170
9996,fcb5a9df-d04e-46bd-a3c4-b1c2bb15570c,Revandra Zaedani,https://play-lh.googleusercontent.com/a/ACg8oc...,Jadiin genap 50 k ajadah nanggung amat,1,0,None,2024-12-04 13:41:51,None,None,None
9997,316d5de4-97b5-435d-9597-723701c3c84e,yanto,https://play-lh.googleusercontent.com/a/ACg8oc...,Kamu 😀,1,0,None,2024-12-04 11:18:27,None,None,None
9998,7e32cf36-9300-4eec-8553-09dd662fb9b3,Chandra Ade Putra Simanjuntak SH,https://play-lh.googleusercontent.com/a-/ALV-U...,Ok,5,0,8.140.1 build 14 51170,2024-12-04 11:16:30,None,None,8.140.1 build 14 51170
9999,1f22e588-3424-412b-a67a-b634d8b68c25,Arlizah Rizki Raya Ramadhani,https://play-lh.googleusercontent.com/a-/ALV-U...,"Gabisa bikin akun ,gtw knp,gajelas gitu",3,0,8.140.1 build 14 51170,2024-12-04 07:28:15,None,None,8.140.1 build 14 51170

In [17]:
len(df_busu.index)

10000

#ambil data yang dibutuhkan

In [18]:
df_busu[['userName', 'score', 'at', 'content']].tail()

,userName,score,at,content
9995,Agus Helmi MK,5,2024-12-04 13:50:01,Mantap
9996,Revandra Zaedani,1,2024-12-04 13:41:51,Jadiin genap 50 k ajadah nanggung amat
9997,yanto,1,2024-12-04 11:18:27,Kamu 😀
9998,Chandra Ade Putra Simanjuntak SH,5,2024-12-04 11:16:30,Ok
9999,Arlizah Rizki Raya Ramadhani,3,2024-12-04 07:28:15,"Gabisa bikin akun ,gtw knp,gajelas gitu"

In [19]:
my_df =df_busu[['userName', 'score', 'at', 'content']]

#simpan dataset ke dalam file

In [20]:
my_df.to_csv("Datasetnetflix.csv", index = False)