In [1]:
!pip install pandas
!pip install numpy
!pip install nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [2]:
#untuk komputasi numerik
import numpy as pd

#memproses pengolahan text (Natural Language Toolkit)
import nltk

#membantu memepermudah manipulasi data teks
import string

#mencari pola kata spesifik yang dicari (Reguler Expression - Regex)
import re

#hilangkan notif karena migrasi dari python
import warnings
warnings.filterwarnings('ignore')

In [7]:
#import Library yang dibutuhkan
import pandas as pd
from tqdm import tqdm, notebook
import warnings
warnings.filterwarnings('ignore')

pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)
pd.pandas.set_option('display.max_colwidth', None)
pd.pandas.set_option('display.width', None)

In [8]:
df = pd.read_csv('/content/Datasetnetflix.csv')
df.head()

,userName,score,at,content
0,Pengguna Google,1,2026-06-07 16:41:41,apk gaje buat masuk daftar aja du di persulit
1,Pengguna Google,1,2026-06-07 16:00:54,"baru mau daftar aja udah dipersulit, muter2 email balik ke apk muter lagi ke email balik ke apk lagi, gitu aja trus"
2,Pengguna Google,4,2026-06-07 15:39:58,film nya ga terlalu banyak
3,Pengguna Google,4,2026-06-07 15:16:42,mana kung Fu panda 3
4,Pengguna Google,5,2026-06-07 15:03:14,menghibur👍👍🔥🤩

In [13]:
df['sentiment'] = df['score'].map({1.0:0,2.0:0,3.0:1, 4.0:1, 5.0:1})
df.head()

,userName,score,at,content,sentiment
0,Pengguna Google,1,2026-06-07 16:41:41,apk gaje buat masuk daftar aja du di persulit,0
1,Pengguna Google,1,2026-06-07 16:00:54,"baru mau daftar aja udah dipersulit, muter2 email balik ke apk muter lagi ke email balik ke apk lagi, gitu aja trus",0
2,Pengguna Google,4,2026-06-07 15:39:58,film nya ga terlalu banyak,1
3,Pengguna Google,4,2026-06-07 15:16:42,mana kung Fu panda 3,1
4,Pengguna Google,5,2026-06-07 15:03:14,menghibur👍👍🔥🤩,1

In [18]:
#Ambil teks untuk kita labelkan
dataku = pd.DataFrame(df[['content','sentiment']])
dataku.head(10)

,content,sentiment
0,apk gaje buat masuk daftar aja du di persulit,0
1,"baru mau daftar aja udah dipersulit, muter2 email balik ke apk muter lagi ke email balik ke apk lagi, gitu aja trus",0
2,film nya ga terlalu banyak,1
3,mana kung Fu panda 3,1
4,menghibur👍👍🔥🤩,1
5,sering error,0
6,Aplikasi bagus,1
7,"Gagal login, padahal di hp ancar, tp pas login di tab, malah katanya erangkat ga mendukung !!!!",0
8,"banyak film bagus di hilangkan lebih dulu padahal ada film yang menurut saya jelek dan ada adegan seksnya malah tidak di hapus padahal fimn yang di hilangkan lebih dulu itu film yang sangat bagus, kalian terlalu naif dan egois!!",0
9,loading ga jelas,0

In [19]:
my_df = dataku[['content','sentiment']]

In [20]:
#simpan Dataset ke dalam File
my_df.to_csv("label_Netflix.csv", index = False)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   userName   10000 non-null  object
 1   score      10000 non-null  int64
 2   at         10000 non-null  object
 3   content    10000 non-null  object
 4   sentiment  10000 non-null  int64
dtypes: int64(2), object(3)
memory usage: 390.8+ KB